version: 2
updates:
  # github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # mets-parser
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
