# image used for the healthcheck binary
FROM golang:1.18.0-alpine3.14 AS build
WORKDIR /go/src/healthcheck/

COPY healthcheck.go .
COPY go.mod .
COPY go.sum .

RUN go build -ldflags '-w -s' -o /healthcheck /go/src/healthcheck/

FROM alpine:3.15.3
COPY --from=build /healthcheck /healthcheck
