# image used for the healthcheck binary
FROM golang:1.17.5-bullseye  AS build
WORKDIR /go/src/healthcheck/

COPY healthcheck.go .
COPY go.mod .
COPY go.sum .

RUN go build -ldflags '-w -s' -o /healthcheck /go/src/healthcheck/

FROM debian:11.1-slim
COPY --from=build /healthcheck /healthcheck
