name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  golanglint:
    name: Lint the healthcheck script
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: v1.31
          working-directory: healthcheck
