name: continuous-integration

on:
  push:
    branches:
      - develop

jobs:
  golanglint:
    name: Lint the healthcheck script
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v1.31

  dockerfilelint:
    name: Dockerfile lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Hadolint with reviewdog
        uses: reviewdog/action-hadolint@v1.25
