name: continuous-integration

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  golanglint:
    name: Lint the healthcheck script
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v1.31

  dockerfilelint:
    name: Dockerfile lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Hadolint with reviewdog
        uses: reviewdog/action-hadolint@v1.25

  gobuild:
    name: Build Go
    runs-on: ubuntu-20.04
    needs: golanglint
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17.2
      -
        run: |
          go build
        
