name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    name: "[${{matrix.flavor}}] Build and release"
    strategy:
      fail-fast: true
      matrix:
        include:
          -
            flavor: buster
            latest: true
          -
            flavor: alpine
            latest: false
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2.3.5

      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          labels: |
            org.opencontainers.image.description=Healthcheck binary specific for Next.js [${{matrix.flavor}}]
          images: |
            ghcr.io/bratteng/healthcheck
            bratteng/healthcheck
          flavor: |
            latest=${{matrix.latest}}
          tags: |
            type=raw,value=${{matrix.flavor}}

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.${{ matrix.flavor }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
